package com.example.hibernate.model;
// Generated 27 ene 2026, 17:26:14 by Hibernate Tools 6.6.4.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * Contactinfo generated by hbm2java
 */
@Entity
@Table(name="contactinfo"
    , uniqueConstraints = {@UniqueConstraint(columnNames="email"), @UniqueConstraint(columnNames="profesorId")} 
)
public class ContactInfo  implements java.io.Serializable {


     private Integer id;
     private Profesor profesor;
     private String email;
     private String tlfMovil;

    public ContactInfo() {
    }

	
    public ContactInfo(Profesor profesor, String email) {
        this.profesor = profesor;
        this.email = email;
    }
    public ContactInfo(Profesor profesor, String email, String tlfMovil) {
       this.profesor = profesor;
       this.email = email;
       this.tlfMovil = tlfMovil;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="profesorId", unique=true, nullable=false)
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }

    
    @Column(name="email", unique=true, nullable=false, length=255)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="tlf_movil", length=15)
    public String getTlfMovil() {
        return this.tlfMovil;
    }
    
    public void setTlfMovil(String tlfMovil) {
        this.tlfMovil = tlfMovil;
    }




}


